package com.lamadridblandongoyes.pronotes

const val DELETE_LABEL_INTERACTOR = "DELETE_LABEL_INTERACTOR"
const val UPDATE_LABEL_INTERACTOR = "UPDATE_LABEL_INTERACTOR"
const val DELETE_NOTE_INTERACTOR = "DELETE_NOTE_INTERACTOR"
const val UPDATE_NOTE_INTERACTOR = "UPDATE_NOTE_INTERACTOR"
const val NOTES_NUMBER_OF_COLUMNS = 2
const val INTENT_EXTRA_NOTE = "INTENT_EXTRA_NOTE"
const val ADDING_NOTE_REQUEST_CODE = 0