package com.lamadridblandongoyes.pronotes

const val DELETE_LABEL_INTERACTOR = "DELETE_LABEL_INTERACTOR"
const val UPDATE_LABEL_INTERACTOR = "UPDATE_LABEL_INTERACTOR"
const val DELETE_NOTE_INTERACTOR = "DELETE_NOTE_INTERACTOR"
const val UPDATE_NOTE_INTERACTOR = "UPDATE_NOTE_INTERACTOR"