package com.lamadridblandongoyes.pronotes

const val DELETE_LABEL_INTERACTOR = "DELETE_LABEL_INTERACTOR"
const val UPDATE_LABEL_INTERACTOR = "UPDATE_LABEL_INTERACTOR"
const val DELETE_NOTE_INTERACTOR = "DELETE_NOTE_INTERACTOR"
const val UPDATE_NOTE_INTERACTOR = "UPDATE_NOTE_INTERACTOR"
const val NOTES_NUMBER_OF_COLUMNS = 2
const val INTENT_EXTRA_NOTE = "INTENT_EXTRA_NOTE"
const val INTENT_EXTRA_LABEL_LIST = "INTENT_EXTRA_LABEL_LIST"
const val INTENT_EXTRA_LABEL = "INTENT_EXTRA_LABEL"
const val ADDING_NOTE_REQUEST_CODE = 0
const val EDITING_NOTE_REQUEST_CODE = 1
const val ADDING_LABEL_REQUEST_CODE = 0
const val EDITING_LABEL_REQUEST_CODE = 1
const val REMOVE_NOTE_TITLE = "Removing note"
const val REMOVE_NOTE_SUBTITLE = "Are you sure you want to delete this note?"
const val REMOVE_LABEL_TITLE = "Removing label"
const val REMOVE_LABEL_SUBTITLE = "Are you sure you want to delete this label?"
const val TAB_TITLE_NOTES = "Notes"
const val TAB_TITLE_LABELS = "Labels"
const val NOTE_VALIDATION_ERROR_TITLE = "Error saving note"
const val NOTE_VALIDATION_ERROR_SUBTITLE = "You can't have both empty title and subtitle."
const val LABEL_VALIDATION_ERROR_TITLE = "Error saving label"
const val LABEL_VALIDATION_ERROR_SUBTITLE = "You can't have an empty title."
const val NEW_NOTE_TITLE = "New Note"
const val NEW_NOTE_SUBTITLE = "Let's get our new note!"
const val EDIT_NOTE_TITLE = "Edit Note"
const val EDIT_NOTE_SUBTITLE = "Let's edit the old note!"
const val NEW_LABEL_TITLE = "New Label"
const val NEW_LABEL_SUBTITLE = "Let's get our new label!"
const val EDIT_LABEL_TITLE = "Edit Label"
const val EDIT_LABEL_SUBTITLE = "Let's edit the old label!"
const val LABEL_COLOR = "Label color"
const val NO_LABELS_TITLE = "There are no labels yet"
const val NO_LABELS_SUBTITLE = "You must first create a label before creating a new note"
